'use client';

import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import { TransportProvider } from "@connectrpc/connect-query";
import { createConnectTransport } from "@connectrpc/connect-web";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };


const finalTransport = createConnectTransport({
  baseUrl: "http://localhost:8080",
});

const queryClient = new QueryClient();


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <TransportProvider transport={finalTransport}>
          <QueryClientProvider client={queryClient}>
            {children}
          </QueryClientProvider>
        </TransportProvider>
      </body>
    </html>
  );
}
